version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - C:/Users/gulat/Downloads/TodoListPhonepe/config.yml:/app/config.yml
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: phonepe
    ports:
      - "3305:3306"
